# Generated by Django 2.0.7 on 2019-10-22 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='discription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='title',
            field=models.CharField(max_length=120),
        ),
    ]
