# Generated by Django 2.0.7 on 2019-10-22 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_auto_20191022_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='featured',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
