# Generated by Django 2.0.7 on 2019-10-22 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_restaurant_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='summary',
            field=models.TextField(),
        ),
    ]
