# Generated by Django 2.0.7 on 2019-10-22 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_auto_20191022_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='summary',
            field=models.TextField(blank=True),
        ),
    ]
